


export const palavras = [
    {nome: 'Natação', id: 1},
    {nome: 'Vela', id: 2},
    {nome: 'Polo Aquático', id: 3},
    {nome: 'Nado Sincronizado', id: 4},
    {nome: 'Voleibol', id: 5},
    {nome: 'Handebol', id: 6},
    {nome: 'Basquete', id: 7},
    {nome: 'Futsal', id: 8},
    {nome: 'Futebol', id: 9},
    {nome: 'Beisebol', id: 10},
    {nome: 'Tênis', id: 11},
    {nome: 'Futebol Americano', id: 12},
    {nome: 'Boxe', id: 13},
    {nome: 'Muay Thai', id: 14},
    {nome: 'Jiu-Jitsu', id: 15},
    {nome: 'Luta Livre', id: 16},
    {nome: 'Corrida', id: 17},
    {nome: 'Salto com vara', id: 18},
    {nome: 'Lançamento de Dardo', id: 19},
    {nome: 'Lançamento de Disco', id: 20},
    {nome: 'NFL', id: 21},
    {nome: 'Brasileirão', id: 22},
    {nome: 'Libertadores', id: 23},
    {nome: 'Us Open', id: 24},
    {nome: 'Copa do Brasil', id: 25},
    {nome: 'Superliga', id: 26},
    {nome: 'Fórmula 1', id: 27},
    {nome: 'Paraolimpíadas', id: 28},
    {nome: 'Copa do Mundo', id: 29},
    {nome: 'Doping', id: 30},
    {nome: 'Brasil nas Olimpíadas', id: 31},
    {nome: 'Copa do Mundo Feminina', id: 32},
    {nome: 'E-Sports', id: 33},
    {nome: 'Olimpíadas de Inverno', id: 34},
    {nome: 'Assédio', id: 35},
    {nome: 'Paralimpícos', id: 36},
    {nome: 'Esportes Mistos', id: 37},
    {nome: 'Copa da Marta', id: 38},
    {nome: 'Transfobia', id: 39},
    {nome: 'Venda do Neymar', id: 40},
    {nome: 'Jogos Pan-americanos', id: 41},
]